name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Call Release Workflow
    permissions:
      contents: read
      packages: write
    uses: ethn1ee/pi/.github/workflows/release.yaml@main
    with:
      deployment: pi-api-stats
      namespace: pi-api-stats
      image_name: pi-api-stats
      image_tag: ${{ github.sha }}
    secrets: inherit
